Handle env vars which are convertible to string
To change an environment variable, you must be set its value as a string
otherwise you get an exception:

  TypeError: no implicit conversion of Fixnum into String

This change attemptst to convert env var values in the process environment
to strings.